### ISSUE TITLE
BDT Variable Third-Highest Csv

### ISSUE THREAD

**Issue by pamelallerena** [HEP-EPN/FourTopsCMSOpenData#10]
The plot for the variable in question exhibits a limited range of values, predominantly concentrated near [zero](https://github.com/HEP-EPN/FourTopsCMSOpenData/blob/main/Notebooks/SingleLepton_Muon/Muon_Plots.ipynb). Notably, there are no specific plots provided in the Analysis Note (AN) for this variable. Considering that, maybe it shouldn't be considered for the analysis. An evaluation is necessary to determine if the other [variables](https://github.com/HEP-EPN/FourTopsCMSOpenData/wiki#bdt) adequately capture the necessary information.
@caredg

**Comment by caredg** [comment]
I think it can probably be dropped.
