### ISSUE TITLE
Description of reason for BDT variables 

### ISSUE THREAD

**Issue by caredg** [HEP-EPN/FourTopsCMSOpenData#7]
I think it would be a good idea to describe the physical reason why the variables [here](https://github.com/HEP-EPN/FourTopsCMSOpenData/wiki#bdt) are considered.  To do this one can think of the decay products of the main background `ttbar` and compare it to the signal `tttt` and come up with the simple explanation if it is not already in the AN. @pamelallerena

**Comment by pamelallerena** [comment]
I agree with you, Edgar. I have included that info. However, I'm unsure about how to explain the physical reason behind using the CSV variable since the AN only mentioned it as one of the best variables for the BDT.

**Comment by caredg** [comment]
Give it a try and we may comment later...
